/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_lzu_oss_tcp_im_lib_Encrypt */

#ifndef _Included_cn_edu_lzu_oss_tcp_im_lib_Encrypt
#define _Included_cn_edu_lzu_oss_tcp_im_lib_Encrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_lzu_oss_tcp_im_lib_Encrypt
 * Method:    mkrand
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_edu_lzu_oss_tcp_1im_lib_Encrypt_mkrand
  (JNIEnv *, jclass);

/*
 * Class:     cn_edu_lzu_oss_tcp_im_lib_Encrypt
 * Method:    mkpvtkey
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_edu_lzu_oss_tcp_1im_lib_Encrypt_mkpvtkey
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     cn_edu_lzu_oss_tcp_im_lib_Encrypt
 * Method:    encrypt
 * Signature: (Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_cn_edu_lzu_oss_tcp_1im_lib_Encrypt_encrypt
  (JNIEnv *, jclass, jstring, jintArray);

/*
 * Class:     cn_edu_lzu_oss_tcp_im_lib_Encrypt
 * Method:    decrypt
 * Signature: (Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_cn_edu_lzu_oss_tcp_1im_lib_Encrypt_decrypt
  (JNIEnv *, jclass, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
